name: Docker CI

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 1 * * 0'


jobs:
  Source:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login Docker
      run: echo ${{ secrets.DOCKER_PASSWORD }} |  docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Build
      run: docker build --file Dockerfile --tag cyb3rjak3/har_analyzer:latest --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` --build-arg VCS_REF=`git rev-parse --short HEAD` .

    - name: Push To Docker
      run: docker push cyb3rjak3/har_analyzer:latest