name: Docker CI

on:
  push:
    branches:
      - main
  schedule:
    - cron: '5 8 * * 0'


jobs:
  Docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Login
      run: echo ${{ secrets.DOCKER_PASSWORD }} |  docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Build
      run: docker build --file Dockerfile --tag cyb3rjak3/har_analyzer:latest --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` --build-arg VCS_REF=`git rev-parse --short HEAD` .

    - name: Push
      run: docker push cyb3rjak3/har_analyzer:latest

  GitHub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com --username cyb3r-jak3  --password-stdin

      - name: Build
        run: ocker build --file Dockerfile --tag docker.pkg.github.com/cyb3r-jak3/har_analyzer/har_analyzer:latest --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` --build-arg VCS_REF=`git rev-parse --short HEAD` .

      - name: Push
        run: docker push docker.pkg.github.com/cyb3r-jak3/har_analyzer/har_analyzer:latest