name: Python CI

on:
  push:
    paths:
      - "app/**"
      - ".github/workflows/python.yml"
      - "requirements.txt"
      - "requirements-dev.txt"
#    tags-ignore:
#      - "v**"

jobs:
  Python:
    runs-on: ubuntu-latest
    services:
      # Label used to access the service container
      redis:
        # Docker Hub image
        image: redis:6.2.3-alpine
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps port 6379 on service container to the host
          - 6379:6379
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.8

    - uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: pip-${{ hashFiles('**/requirements.txt', '**/requirements-dev.txt') }}

    - name: Install Dependanices
      run: |
        pip install --upgrade pip wheel
        pip install -r requirements-dev.txt

    - name: Lint
      run: make lint

    - name: Test
      run: make test
      env:
        REDIS_URL: "redis://localhost:6379"
