name: Python CI

on:
  push:
    paths:
      - "app/**"
      - ".github/workflows/python.yml"
      - "requirements.txt"
      - "requirements-dev.txt"

jobs:
  Python:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.8

    - uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: pip-${{ hashFiles('**/requirements.txt', '**/requirements-dev.txt') }}

    - name: Install Dependanices
      run: |
        pip install --upgrade pip wheel
        pip install -r requirements-dev.txt

    - name: Lint
      run: make lint
